# Generated by Django 6.0 on 2025-12-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.AddField(
            model_name='menu',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(default='main', max_length=20),
        ),
    ]
